config/routes.rb
Prayers::Application.routes.draw do

  resources :users

  root to: "static#home"

  match '/signup', to: 'users#new'

  match '/help', to: "static#help"

  match '/about', to: "static#about"

  match '/contact', to: "static#contact"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }

  VALID_EMAIL_REGEXP = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEXP },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new( params[:user] )
    if @user.save
      # Successful save
      flash[:success] = 'Welcome to the Prayer Reminder Service'
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

   def full_title(page_title)
     base_title = "Ruby on Rails Sample App"
     if page_title.empty?
       base_title
     else
       "#{base_title} | #{page_title}"
     end
   end

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gid = Digest::MD5::hexdigest(user.email.downcase)
    #gurl = "https://secure.gravatar.com/avatars/#{gid}.png"
    gurl = 'http://mudconnect.com/images/avatars/icculus1.jpg'
    image_tag(gurl, class: 'gravatar' )
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://jesusdiedforusall.com">jesusdiedforusall prayer reminders</a> by Andrew Cowan
  </small>

  <nav>
    <ul>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "sample_app", '#', id: 'logo' %>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Help', help_path %></li>
            <li><%= link_to 'Sign In', '#' %></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  

app/views/layouts/_shim.html.erb
  <!-- [if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></SCRIPT>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title( yield(:title))  %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>

</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |k,v| %>
      <div class='alert alert-<%= k %>'><%= v %></div>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
    
    <%= debug(params) if Rails.env.development? %>
  </div>


</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class='alert alert-error'>
      The form contains <%= pluralize( @user.errors.count, 'error' ) %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide( :title, 'Sign Up') %>

<h1>Sign Up</h1>

<div class='row'>
  <div class='span6 offset3'>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, 'Confirmation' %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit 'Create my account', class: 'btn btn-large btn-primary' %>
    <% end %>
  </div>

</div>

app/views/users/show.html.erb
<% provide( :title, @user.name ) %>

<div class='row'>
  <aside class='span4'>
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>